export enum GlobalResponse {
    AUTH_INVALID_PASSWORD_OR_MAIL = "email ou senha inválidos",
    USER_NOT_FOUND = "Usuário não encontrado.",
    USER_LOGGED = "Usuário logado com sucesso!",
    USER_EXPIRED = "Seu plano expirou, renove seu acesso!",
    USER_INCORRECT_PASSWORD = "Senha incorreta.",
    USER_NOT_AUTHORIZED = "Usuário não autorizado.",
    USER_PAYMENT_REQUIRED = "Pague para acessar a plataforma.",
    USER_PAYMENT_REMOVED = "Pagamento removido. Por favor, renove seu plano novamente ou contate o desenvolvedor.",
    USER_PAYMENT_REMOVED_BY_ADM = "Pagamento removido por um administrador. Contate o desenvolvedor.",

    USER_NOTIFY_SENDER = "notificação enviada com sucesso!",
    USER_ALREADY_EXISTS = "usuário já existe.",
    USER_CREATED = "usuário criado com sucesso!",
    USER_COBRANCE_NOT_FOUND = "cobrança não encontrada.",
    USER_CREATE_ERROR = "erro ao criar usuário.",
    USER_PROFILE_UPDATED = "perfil atualizado com sucesso.",
    USER_VALIDATED = "usuário validado com sucesso.",
    USER_INVALID_CODE = "código inválido.",
    USER_ALREADY_VALIDATE = "usuário já validado.",
    USER_IS_ADMIN = "usuário já é um admin!",
    USER_IS_USER = "usuário já é um usuário comum!",
    USER_PROMOTED = "usuário promovido com sucesso",
    USER_DEMOTED = "usuário demitido com sucesso.",

    USER_AUTODELETE = "vocẽ não pode se auto deletar.",
    USER_DELETED = "usuário deletado com sucesso.",

    USER_DELETE_ERROR = "erro ao deletar usuário.",
    USER_UPDATE_ERROR = "erro ao atualizar usuário",
    USER_UPDATED = "usuário atualizado.",
    USER_NEVER_MODIFY = "nenhuma modificação feita.",

    EMAIL_ERROR = "erro ao enviar email.",
    YOU_ARE_ADMIN = "Você é um administrador, não pode fazer isso, meu chapa!",
    PLAN_CANCEL = "pagamento cancelado.",
    PLAN_ALREADY_CANCELED = "cobrança já está cancelada.",

    PLAN_INVALID = "Plano inválido. Contate o desenvolvedor.",
    PLAN_VALID = "Seu plano está ativo.",
    PLAN_NOT_FOUND = "Plano não encontrado.",
    PLAN_LOAD_PAYMENT = "Aguardando seu pagamento para liberação de acesso.",
    PLAN_INVALID_ACTION = "Ação indisponível",
    PLAN_LOAD_PAYMENT_CHANGE = "Aguardando seu pagamento para liberação de acesso, da troca de plano.",
    PLAN_ALREADY = " esse plano já está assinado.",

    BOT_NOT_FOUND = "Bot não encontrado.",
    BOT_SLEEP_ON = "Bot desligado.",
    BOT_SLEEP_OFF = "Bot ligado.",
    BOT_IN_FLOW = "fluxo iniciado",
    BOT_EXISTS = "Bot já existe.",
    INVALID_PATH = "Caminho inválido.",
    INVALID_TYPE = "Tipo inválido.",
    INVALID_TELEGRAM_PARAMS = "Parâmetros inválidos do Telegram.",
    API_KEY_REQUIRED = "A chave da API é obrigatória com o tipo TelBot.",
    INVALID_API_KEY = "Chave de API inválida do TelBot.",
    INVALID_MODE_TYPE = "Tipo de modo inválido.",
    INVALID_BOT_TYPE = "Tipo de bot inválido.",
    BOT_CREATED = "O bot foi criado com sucesso.",
    UPDATE_OBSERVER_SUCCESS = "A integração do observador foi atualizada com sucesso.",
    BOT_NOT_EXISTS = "Bot não existe.",
    BOT_ONLINE_NOT_FOUND = "não está online",
    SEND_MESSAGE_ERROR_BAD_REQUEST = "informações requeridas.",
    SEND_ERROR_TYPE = "tipo de mensagem não suportado.",
    SEND_ERROR_MIMETYPE = "mimetype é requerido.",

    SEND_MESSAGE_SUCESS = "mensagem enviada",
    PATH_IMMUTABLE = "O caminho não pode ser alterado.",
    MODE_IMMUTABLE = "O modo não pode ser alterado.",
    TYPE_IMMUTABLE = "O tipo não pode ser alterado.",
    BOT_UPDATED = "Bot atualizado com sucesso.",
    CONNECT_BOTS_SUCCESS = "Bots conectados com sucesso.",
    DISCONNECT_BOTS_SUCCESS = "Bots desconectados com sucesso.",
    INVALID_BOT_TYPE_ACTION = "Ação de tipo de bot inválida.",
    INVALID_CHAT_ID = "ID de bate-papo inválido.",
    GROUP_NOT_FOUND = "Grupo não encontrado na lista.",
    GROUP_ALREADY_IN_LIST = "Grupo já está na lista.",
    GROUP_ADDED_TO_LIST = "Grupo adicionado à lista com sucesso.",
    GROUP_REMOVED_FROM_LIST = "Grupo removido da lista com sucesso.",
    INVALID_JID = "JID inválido.",
    INVALID_BOT_TYPE_ACTION_PHONE = "Ação de tipo de bot inválida para atualização de telefone.",
    BOT_PHONE_UPDATED = "O telefone do bot foi atualizado com sucesso.",
    BOT_DELETED = "O bot foi excluído com sucesso.",
    BOT_DELETED_EMERGENCY = "O bot foi excluído com sucesso (modo de emergência).",

    FLOW_ERROR_PARAMS = "parametros da mensagem [INDEX] do tipo [TYPE] inválidos.",
    FLOW_INVALID_TYPE = "o tipo [TYPE] na mensagem [INDEX] é inválido.",
    FLOW_NOT_FOUND = "fluxo não encontrado!",
    FLOW_STOP = "fluxo parado!",
    FLOW_ERROR_BUFFER = "erro na mensagem [INDEX], porfavor refaça o upload.",
    CONTACT_LIST_EXISTS = "a lista de contatos com este nome já existe.",
    CONTACT_LIST_CREATED = "lista de contato criada!",
    CONTACT_LIST_UPDATE = "lista de contatos atualizada",
    CONTACT_LIST_NOT_FOUND = "lista de contatos não encontrada",
    CONTACT_LIST_DELETED = "lista de contatos deletada.",
    FLOW_OR_LIST_NOT_FOUND = "fluxo ou lista de contatos não encontrados",
    CAMPAING_INIT = "campanha iniciada",
    CONTACT_NOT_CHAT_ID = "o contato [INDEX] não possui chatId",
    FLOW_TIME_OF_TIMER_NOT_FOUND = "o timer do fluxo está incorreto, é necessário informar o tempo em segundos e o tempo de delays.",
    FLOW_TIMER_IS_REQUIRED = "defina um timer para o fluxo!",
    FLOW_MESSAGE_TIMER_NOT_FOUND = "a mensagem para final de tempo não existe.",
    DELAY_MIN = "o delay do fluxo deve ser no minimo 5 segundos e no máximo 3 minutos.",
    BOT_FLOW_ASSOCIATE = "fluxo associado com sucesso!",
    FLOW_TIMER_MAX = "o tempo de espera de um fluxo deve ter no máximo 3 horas",
    FLOW_CLEAR_RESPONSES = "respostas do fluxo limpas.",
    BOT_FLOW_ASSOCIATE_OFF = "fluxo associado removido"
}